/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.instamint.services.ds;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;
import java.util.Properties;

public class App {
    public void start() throws InterruptedException {
        new Thread(new Consumer()).start();
        Thread.sleep(1000);
        new Thread(new Producer()).start();

    }

    public static void main(String[] args) throws InterruptedException {
        new App().start();
    }
}
